공용 Container/Profile component, 찜 기능/애니메이션 및 라인 애니메이션 추가
shchoon/dalleam pull request #17
Opened 2024-09-12 01:39 UTC by shchoon

## #️⃣연관된 trello 작업
- 공용 Container component & test code 구현
- 찜 기능/애니메이션 & test code 구현
- 정원 대비 참여자 수에 따른 line 애니메이션 & test code 구현
- 공용 프로필 컴포넌트 & test code 구현

## 🔎 작업 내용

### 작업한 기능 모두 공용 컴포넌트로 분리

###  공용 Container
- 상세 모임 정보를 기반으로 구현
- 참여자 5(최소인원)인 이상인 경우 '개설 확정' text와 함께 check Icon 노출
- 참여자 5인 미만인 경우 '개설 확정' text, checkIcon 미노출

### 찜 기능/애니메이션
- 찜 아이콘 클릭시 localStorage의 saved value를 참조해 추가/삭제 기능 구현
- 찜 하지 않은 상태에서 HeartIcon 클릭시 2초 동안 애니메이션 동작

### Line Animation 
- 렌더링 시 2초 동안 참여자/정원의 비율에 맞춰 line이 색칠됨
-  참여자 수 === 정원 인 경우 'orange-400' 색상 적용
- 참여자 < 정원 인 경우 'orange-600' 색상 적용

### 공용 프로필
- usedIn(사용되는 페이지), image(null | stringg)를 props로 받아 기본 프로필 또는 개인 프로필 이미지를 사용되는 페이지에 맞는 사이즈로 노출

  <br/>

## 📸 이미지 첨부
![defaultProfile](https://github.com/user-attachments/assets/1a42b7b9-8503-41a6-8199-3388376621a7)
<br/>
![lineExpandOrange](https://github.com/user-attachments/assets/c7036f4f-7627-4f00-9628-6502d1ff9eaf)
<br/>
![featSsaved](https://github.com/user-attachments/assets/84ee75a7-3669-4033-8044-8c9fdb730d19)
<br/>
![expandLine](https://github.com/user-attachments/assets/78bb2aee-be7a-4f49-8d0f-3d6dac3b8565)

스크릿샷 이슈로 이미지에는 라인 색상 변경이 적용이 안되어 있는데 실제 코드는 잘 적용되어 있습니다! 
<br/>

## 💬리뷰 요구사항(선택)

- Profile component에서 같은 default image라도 각 페이지에서 쓰이는 사이즈가 달라서 usedIn props로 조건을 나눠뒀는데 좀 더 간결하고 좋은 방법이 있으시면 말씀해주시면 감사하겠습니다!

2024-09-12 02:05 UTC, Simon1476 reviewed
HomePage(/)는 담당하는 인원이 따로 있을 것이기 때문에
테스트하시는 건 로컬에서만 하시고 경로에 사용되는 페이지 파일들은
자신의 담당 페이지만 커밋 하는 게 좋을 것 같습니다.

2024-09-12 09:26 UTC, Simon1476 requested changes

2024-09-12 09:26 UTC, Simon1476 commented on app/page.tsx
HomePage(/)는 담당하는 인원이 따로 있을 것이기 때문에
테스트하시는 건 로컬에서만 하시고 경로에 사용되는 페이지 파일들은
자신의 담당 페이지만 커밋 하는 게 좋을 것 같습니다.

2024-09-12 09:26 UTC, Simon1476 commented on components/container/Container.test.tsx
주석 처리된 코드는 사용되지 않는 코드이기 때문에 불필요하게 코드 베이스를 복잡하게 만들 수 있을 것 같아요.
그리고 지금 보다 여러 개발자가 협업하는 프로젝트라면 더욱더 주석 처리된 코드가 다른 개발자분들이 헷갈리실 것 같습니다. 주석 처리된 코드를 보면, "이 코드를 다시 사용해야 하는지?", "왜 주석 처리된 건지?"에 대한 질문이 생기지 않을까 생각합니다.

2024-09-12 09:26 UTC, Simon1476 commented on components/container/Container.tsx
gatheringDetails && gatheringDetails.participantCount > 이런 형식으로 gatehringDeatails의 존재 여부를 확인하셔서 데이터를 표시하시는데 모든 곳에서 조건을 확인하고 있지 않은 것 같고  gatheringDetails 데이터를 다른 코드를 실행하기 전 제일 먼저 null 인지 확인하는 게 더 좋을 것 같습니다.

2024-09-12 09:26 UTC, Simon1476 commented on components/profile/Profile.tsx
usedIn 타입이 'navbar', 'container', 'myPage' 3가지 문자열이 사용되는데 유니온 타입을 사용하시면 더 자세하게 타입 검사를 할 수 있을 것 같아요.

props 타입 이름도 Iprops에서 Props 이렇게 변경하시면 될 것 같습니다.

반복되는 return문과 null 체크도 수정하시면 좋을 것 같습니다.

2024-09-12 09:26 UTC, Simon1476 commented on components/profile/Profile.test.tsx
이 파일도 다른 파일과 마찬가지로 주석처리는 지우시면 좋을 것 같습니다!

2024-09-12 09:26 UTC, Simon1476 commented on components/animation/expandLine/ExpandLine.tsx
IProps 타입명을 저희 Convention 규칙인 Props로 변경하셔야 할 것 같아요.
lineWidth state는 string으로 타입을 명시하지 않아도 추론되기 때문에 필요가 없어 보여요.
카드, 컨테이너 컴포넌트에서 사용될 텐데 lineWidth !== '' 조건을 검사할 필요가 없을 수도 있다고 생각이 들어요.
div의 width는 당연히 항상 존재하고 사용하는 컴포넌트에서 데이터가 문제가 있었다면 사용 컴포넌트에서 처리를 했을 것이기 때문이에요.

2024-09-12 09:26 UTC, Simon1476 commented on components/animation/expandLine/ExpandLine.test.tsx
두 번째 it 첫 번째 "참여자 < 정원" 을 "참여자 === 정원"으로 변경하셔야 할 것 같습니다.
오타로 생각이 드네요.
<div style={{ width: '200px' }}> 아래
{' '} < 이 부분도 지워도 될 것 같습니다.
async 키워드도 불필요한 것 같아요.

2024-09-12 09:33 UTC, shchoon commented on components/container/Container.test.tsx
맞는 말씀입니다! 확실하게 사용하지 않을 주석들에 한해서는 지우도록 하겠습니다!

2024-09-12 09:35 UTC, shchoon commented on components/container/Container.tsx
이렇게 조건에서 코드가 길어지는 부분에 대해서 어떻게 해결해야할 지 궁금했었는데 감사합니다. 참고해서 작업할게요!

2024-09-12 09:36 UTC, shchoon commented on components/profile/Profile.tsx
유니온 타입의 개념만 알고 있었는데 지금 기회에 한 번 적용해 보겠습니다!

2024-09-13 08:34 UTC, Simon1476 requested changes

2024-09-13 08:34 UTC, Simon1476 commented on components/profile/Profile.test.tsx
'navbar에서 사용되는 경우 & image === null' 이렇게 작성해 주셨는데  image === null일 때 navbar에서 사용되는 경우 렌더링 이런 식으로 명확하게 해주는 게 좋을 것 같습니다. 
'navbar에서 사용되는 경우 & image === null'  이 한 문장이 조건처럼 이해될 수도 있을 것 같아요.

2024-09-13 08:34 UTC, Simon1476 commented on components/container/Container.test.tsx
testGatheringData1, testGatheringData2 이렇게 변수를 참여 인원조건을 확인하려고 두 변수를 생성 하셨는데 
it문 안에서  스프레드 문법을 이용하여 객체 participantCount만 다르게 값을 생성하여 이용하면 더 깔끔할 것 같아요.

2024-09-13 08:34 UTC, Simon1476 commented on components/animation/saved/Saved.tsx
handleClickSaved 함수에서  값이  없는 경우를 if로 먼저 검사하면  if(saved)를 사용하지 않아도 되니까 가독성이 더 좋아질 것 같아요.

2024-09-13 08:52 UTC, shchoon commented on components/profile/Profile.test.tsx
시몬님 말씀처럼 테스트 이름이 좀 헷갈릴 수도 있겠네요. 수정하겠습니다!

2024-09-13 08:53 UTC, shchoon commented on components/container/Container.test.tsx
스레드로 하니 코드 길이가 많이 줄었네요. 수정 완료했습니다!

2024-09-13 10:49 UTC, shchoon commented on components/animation/saved/Saved.tsx
GPT 참고해보니까 말도 안되게 깔끄한 코드가 되어버렸습니다ㅋㅋㅋ
 falsy 여부에 따라 값을 return  || 연산자를 사용해서 수정했습니다!

2024-09-15 06:00 UTC, Simon1476 approved these changes

2024-09-15 11:40 UTC, merged