모임등록 컴포넌트 구현
shchoon/dalleam pull request #18
Opened 2024-09-16 05:56 UTC by Namyunha

## #️⃣연관된 trello 작업

### 🎱 Trello Doing (리뷰 후 Done)

- 모임 등록하기

### 🎯 Trello Done

- Chip 컴포넌트

- Calendar 컴포넌트

## 🔎 작업 내용

- 캘린더를 통해 날짜 가져오기

- 이미지 업로드

- 모임 등록하기

  <br/>

## 📸 이미지 첨부

![모임 만들기 구현](https://github.com/user-attachments/assets/e1446c9e-8c1f-40bf-9228-d473b3aa2b92)

<br/>

![image](https://github.com/user-attachments/assets/63912158-a4e2-4831-9de5-0093f401f577)

## 💬리뷰 요구사항(선택)

- 컴포넌트만 구현했기 때문에, 추후에 이 컴포넌트 위치를 재조정할 때 (이 모달에 해당하는 페이지가 완성됐을 때) 그 때 css관련 부분을 해결 하려고 합니다.

- 테스트 코드는 시간이 더 걸릴것같아, 제가 맡은 부분을 마저 구현한 뒤에 마무리 하려고 합니다.

2024-09-16 06:26 UTC, Simon1476 requested changes

2024-09-16 06:26 UTC, Simon1476 commented on components/chip/Chip.tsx
forwardRef를 사용하셨는데 forwardRef 사용하면 부모 컴포넌트에서 Chip의 <span> 요소에
직접적으로 접근하여 포커스를 주거나, 스타일을 동적으로 변경하는 등 제어할 필요가 있을 때 사용한다고 알고 있습니다.
페이지를 보면 이 컴포넌트를 이용하여 시간과 날짜를 보여주고 목록 필터링 버튼 역할을 하는 것 같은데 forwardRef가 특별히 필요한 이유와 제가 놓치고 있는 것들이 있으면 말씀해 주시면 감사하겠습니다.

2024-09-16 06:29 UTC, Namyunha commented on components/chip/Chip.tsx
일반적인 dom에 ref를 줄 때는 문제가 없지만, 직접 컴포넌트를 정의하거나 ui같은데에서 쓰이는 컴포넌트에 ref를 걸려고하면 생기는 에러를 해결하기 위해서는 forwardRef를 이용해야 하는 것으로 알고 적용하였습니다,

2024-09-16 06:36 UTC, Simon1476 requested changes

2024-09-16 06:36 UTC, Simon1476 commented on components/chip/Chip.tsx
답변 감사드립니다.
지금의 경우 ref를 거는 상황이 있는건가요?
아니면 추후에  ref를 걸려고하는 상황을 위해서 만들었다고 생각하면 될까요?

2024-09-16 06:42 UTC, Namyunha commented on components/chip/Chip.tsx
![image](https://github.com/user-attachments/assets/4e78c1ee-7aba-4830-83d9-08c203ac0129)

보시면 컨트롤러안에서 Chip을 렌더하게 하고, 그 안에 field를 적용시켰는데 field안에는 ref가 있고, 저렇게 Spread Syntax 형식으로 값을 넣어주면 해당 요소들이 전부 적용되는 것이며 이는 Chip에 ref를 걸어주는 것과도 같기 때문에 사용하게 되었습니다!

2024-09-16 06:59 UTC, Simon1476 commented on components/chip/Chip.tsx
GatheringTimes.tsx에서 사용했군요.
감사합니다!
이해가 잘 됐어요.

2024-09-16 07:04 UTC, Simon1476 requested changes

2024-09-16 07:04 UTC, Simon1476 commented on app/reviews/_components/GatheringService.tsx
GatheringService.map 부분에서 key 속성에 idx(인덱스)를 주셨는데 key는 배열의 항목을 고유하게 식별해야 하니까 idx 대신에 el.value가 더 정확할 것 같습니다.

![image](https://github.com/user-attachments/assets/98bcecd5-4946-4504-b895-eb9311483220)
GatheringServiceType을 따로 만들지 않고 아래처럼 하면 더 깔끔할 것 같습니다!

 const GatheringService: {
    value: GatheringType;
    name: '달램핏:오피스 스트레칭' | '달램핏:마인드풀니스' | '워케이션';
  }[] = [
    { value: 'OFFICE_STRETCHING', name: '달램핏:오피스 스트레칭' },
    { value: 'MINDFULNESS', name: '달램핏:마인드풀니스' },
    { value: 'WORKATION', name: '워케이션' },
  ];

2024-09-16 07:07 UTC, Namyunha commented on app/reviews/_components/GatheringService.tsx
idx는 고유하지 않다고 생각하신 이유가 있으실까요??

2024-09-16 07:10 UTC, Simon1476 commented on app/reviews/_components/GatheringService.tsx
고유하지 않다기 보다는 나중에 배열의 순서가 변경 되더라도 배열의 인덱스는 변경되지만 el.value는 변경되지 않기 때문에 더 정확하다고 생각했어요!

2024-09-16 07:11 UTC, Namyunha commented on app/reviews/_components/GatheringService.tsx
아하! 그 문제가 따로 장애를 유발하는 문제를 생기진 않을거 같아서  특별히 문제가 없다면 유지하도록 하겠습니다!

2024-09-16 07:18 UTC, Namyunha commented on app/reviews/_components/GatheringService.tsx
객체 부분은 시몬님 주신 말씀 처럼 타입 정의해보도록 해도 지금 상황에선 괜찮을거같습니다!

2024-09-19 00:03 UTC, Simon1476 approved these changes

2024-09-19 00:04 UTC, merged